[build]
  command = "pip install -r requirements.txt && streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "streamlit run app.py"
  port = 8501
  publish = "."
